# Generated by Django 4.2.7 on 2023-12-01 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
